---
exclude_paths:
    - ".git/"
    - "**.gif"
    - "**.html"
    - "**.json"
    - "**.png"
    - "**.svg"
    - "**.xml"
    - "**.yaml"
    - "**.yml"
    - "**/bower_components/"
    - "**/boot**css"
    - "**/boot**js"
    - "**/codemirror/"
    - "**/grid/"
engines:
    radon:
        enabled: true
    pep8:
        enabled: true
        checks:
          E501:
            enabled: false
    eslint:
        enabled: true
    csslint:
        enabled: true
ratings:
    paths:
      - "**.py"
      - "**.js"
      - "**.css"
