apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cache
  namespace: tumbo
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 5672
    protocol: ""
    targetPort: 0
  selector:
    service: cache
status:
  loadBalancer: {}
