apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: cache
  name: cache
  namespace: tumbo
spec:
  replicas: 1
  selector:
    service: cache
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cache
    spec:
      containers:
      - image: tutum/redis
        imagePullPolicy: ""
        name: cache
        ports:
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
