apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: app
  name: app
  namespace: tumbo
spec:
  replicas: 1
  selector:
    service: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: app
    spec:
      containers:
      - image: philipsahli/tumbo-server:kubernetes
        imagePullPolicy: "Always"
        name: app
        envFrom:
        - configMapRef:
            name: tumbo-config
        env:
        - name: MODE
          value: web
        - name: JOBSTOREDB_PASS
          valueFrom:
            secretKeyRef:
              name: passwords
              key: jobstoredbpw
        - name: RABBITMQ_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: rabbitmqadminpw
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: redispw
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: passwords
              key: dbpw
        ports:
        - containerPort: 80
        resources: {}
        #volumeMounts:
        #- name: secrets
        #  mountPath: /etc/secrets
        #  readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      #volumes: 
      #- name: secrets
      #  secret:
      #  secretName: redispw
status:
  replicas: 0
