apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: app
  namespace: tumbo
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 80
    protocol: ""
    targetPort: 0
  selector:
    service: app
status:
  loadBalancer: {}
