apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: background
  name: background
  namespace: tumbo
spec:
  replicas: 1
  selector:
    service: background
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: background
    spec:
      containers:
      - envFrom:
        configMapRef:
          name: tumbo-config
      - env:
        - name: MODE
          value: background
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: adminpw
        - name: JOBSTOREDB_PASS
          valueFrom:
            secretKeyRef:
              name: passwords
              key: jobstoredbpw
        - name: RABBITMQ_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: rabbitmqadminpw
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: redispw
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: passwords
              key: dbpw
        image: philipsahli/tumbo-server:kubernetes
        imagePullPolicy: "Always"
        name: background
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
