apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: queue
  namespace: tumbo
spec:
  ports:
  - name: "communication"
    nodePort: 0
    port: 5672
    protocol: ""
    targetPort: 0
  - name: "management"
    nodePort: 0
    port: 15672
    protocol: ""
    targetPort: 0
  selector:
    service: queue
status:
  loadBalancer: {}
