apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: queue
  name: queue
  namespace: tumbo
spec:
  replicas: 1
  selector:
    service: queue
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: queue
    spec:
      containers:
      - image: tutum/rabbitmq
        env:
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: passwords
              key: rabbitmqadminpw
        imagePullPolicy: ""
        name: queue
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
