apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: store
  namespace: tumbo
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 5432
    protocol: ""
    targetPort: 0
  selector:
    service: store
status:
  loadBalancer: {}
