apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cache
  namespace: default
spec:
  ExternalName: ""
  ports:
  - name: ""
    nodePort: 0
    port: 5672
    protocol: ""
    targetPort: 0
  selector:
    service: cache
status:
  loadBalancer: {}
