apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: jobstoredb
  name: jobstoredb
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: jobstoredb
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: jobstoredb
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: store
        - name: DB_USER
          value: store
        - name: SUPERUSER
          value: "true"
        image: philipsahli/postgresql-test
        imagePullPolicy: ""
        name: jobstoredb
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
