apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: background
  namespace: default
spec:
  ExternalName: ""
  ports:
  - name: ""
    nodePort: 0
    port: 80
    protocol: ""
    targetPort: 0
  selector:
    service: background
status:
  loadBalancer: {}
