apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: lb
  namespace: default
spec:
  ExternalName: ""
  ports:
  - name: ""
    nodePort: 0
    port: 8880
    protocol: ""
    targetPort: 0
  selector:
    service: lb
status:
  loadBalancer: {}
